import { OrganizationSettings, FinanceCategory } from '../types';

export const DEFAULT_ORG_SETTINGS: OrganizationSettings = {
  hamletName: 'Ấp Bình Hòa',
  communeName: 'Xã An Nhơn Tây',
  provinceName: 'TP. Hồ Chí Minh',
  address: 'Tổ 2, Đường Bình Hòa, Xã An Nhơn Tây, TP. Hồ Chí Minh',
  phone: '028.3792.0124',
  email: 'apbinhhoa@annhontay.tphcm.gov.vn',
  logoUrl: '',
  hamletLeaderName: 'Nguyễn Văn Hùng',
  financeOfficerName: 'Mai Thị Thúy',
  treasurerName: 'Trần Kim Ngân',
  voucherSettings: {
    incomePrefix: 'PT',
    expensePrefix: 'PC',
    currentYear: 2026,
    templateStandard: 'Quy chuẩn Mẫu C40-BB',
    superiorAgency: 'UBND XÃ AN NHƠN TÂY',
    agencyName: 'BAN ĐIỀU HÀNH ẤP BÌNH HÒA',
    footerNote: '',
    signers: [
      { roleTitle: 'TRƯỞNG ẤP', actionSubtitle: '(Ký, duyệt)', name: 'Nguyễn Văn Hùng' },
      { roleTitle: 'THỦ QUỸ', actionSubtitle: '(Đã nhập/xuất quỹ)', name: 'Trần Kim Ngân' },
      { roleTitle: 'NGƯỜI NỘP/NHẬN', actionSubtitle: '(Ký, ghi rõ họ tên)', name: '' },
    ],
  },
  customClassificationTags: [
    'Hộ nghèo (Nhóm A)',
    'Hộ cận nghèo',
    'Gia đình chính sách (Thương binh)',
    'Người cao tuổi (≥60)',
    'Trẻ em hoàn cảnh khó khăn',
    'Bệnh nặng / Neo đơn',
    'Đang công tác / Lao động',
  ],
  updatedAt: new Date().toISOString(),
  updatedBy: 'Hệ thống',
};

export const DEFAULT_FINANCE_CATEGORIES: FinanceCategory[] = [
  {
    id: 'cat_thu_01',
    name: 'Quỹ An ninh trật tự & Chiếu sáng ngõ xóm',
    type: 'INCOME',
    suggestedAmount: 200000,
    description: 'Thu định kỳ hàng năm phục vụ điện đường, bảo trì camera ngõ xóm',
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cat_thu_02',
    name: 'Quỹ Vì người nghèo & Đền ơn đáp nghĩa',
    type: 'INCOME',
    suggestedAmount: 0,
    description: 'Vận động toàn dân nhân dịp 27/7 và ngày hội đại đoàn kết toàn dân',
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cat_thu_03',
    name: 'Xã hội hóa nâng cấp đường giao thông nông thôn',
    type: 'INCOME',
    suggestedAmount: 350000,
    description: 'Đóng góp làm đường bê tông nông thôn, cống rãnh thoát nước',
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cat_thu_04',
    name: 'Quỹ Khuyến học & Thiếu nhi ấp',
    type: 'INCOME',
    suggestedAmount: 100000,
    description: 'Khen thưởng học sinh giỏi và tổ chức Tết Trung thu cho thiếu nhi',
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cat_chi_01',
    name: 'Chi sửa chữa đường giao thông & chiếu sáng công cộng',
    type: 'EXPENSE',
    suggestedAmount: 4500000,
    description: 'Mua cát đá xi măng, thay bóng đèn LED ngõ xóm',
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cat_chi_02',
    name: 'Chi hỗ trợ đột xuất ma chay, hộ khó khăn hiểm nghèo',
    type: 'EXPENSE',
    suggestedAmount: 1000000,
    description: 'Trợ cấp khẩn cấp theo biên bản họp Ban điều hành Ấp',
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cat_chi_03',
    name: 'Chi văn phòng phẩm & phục vụ họp tiếp xúc cử tri',
    type: 'EXPENSE',
    suggestedAmount: 500000,
    description: 'In ấn tài liệu sinh hoạt chi bộ, họp nhân dân, nước uống',
    isActive: true,
    createdAt: new Date().toISOString(),
  },
];
